name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rust format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal -c rustfmt

      - run: cargo +nightly fmt -- --check

  rust:
    name: Rust lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-protoc@v2

      - run: rustup toolchain install stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build -p sshx-server --release

      - run: cargo build -p sshx --release

      - run: cargo test

      - run: cargo clippy --all-targets -- -D warnings

      - uses: actions/upload-artifact@v4
        with:
          name: linux-rust-binaries
          path: |
            target/release/sshx
            target/release/sshx-server
          if-no-files-found: error

  windows_test:
    name: Client test (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-protoc@v2

      - run: rustup toolchain install stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build -p sshx --release

      - run: cargo test -p sshx

      - uses: actions/upload-artifact@v4
        with:
          name: windows-sshx
          path: target/release/sshx.exe
          if-no-files-found: error

  web:
    name: Web lint, check, and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - run: npm ci

      - run: npm run lint

      - run: npm run check

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [rustfmt, rust, web]
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
